services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flexbox
    ports:
      - "127.0.0.1:5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - postgres

  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Africa/Algiers
      - TZ=Africa/Algiers
    volumes:
      - n8n_data:/home/node/.n8n

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "127.0.0.1:6379:6379"

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "127.0.0.1:27017:27017"

  whatsapp:
    image: devlikeapro/waha:latest
    restart: always
    ports:
      - "3001:3000"
    environment:
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
      - WHATSAPP_API_KEY=abc
      - WHATSAPP_HOOK_EVENTS=message
      - WAHA_LOG_LEVEL=info
    volumes:
      - waha_data:/app/.sessions

volumes:
  postgres_data:
  n8n_data:
  waha_data:
