services:
  app:
    build: .
    ports:
      - "1556:3000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/flexbox
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flexbox
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  whatsapp:
    image: atendai/evolution-api:v1.8.2
    ports:
      - "3001:8080"
    environment:
      - API_KEY=abc
      - AUTHENTICATION_API_KEY=abc
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
    volumes:
      - evo_data:/evolution

volumes:
  postgres_data:
  evo_data:
